### ISSUE TITLE
Nullable Enums Don't Use TypeConverter attribute

### ISSUE THREAD

**Issue by ghost** [t-bruning/UniversalTypeConverter#4]
Hello,

I have a enum that I have defined a custom type converter for. The TypeConverter uses the DescriptionAttribute to convert to and from a string.
Example:
```C#
[TypeConverter(typeof(MyTypeConverter))]
public enum MyEnum {
    [Description("")] General = 1,
    [Description("OTHER")] Other = 2,
}
```

I then have a class that uses it as a nullable type:

```C#
public class MyClass {
    [ProcessValue] // Custom attribute
    public MyEnum? MyEnumValue { get; set; }
}
```

Then for each property in the class that is tagged with the custom attribute (ProcessValue) I get the type of the property and convert a string to the property type and assign it to the property. However, I have to first get the base nullable type before doing it otherwise it does not work:

```C#
// Works
var value = oldValue.To(Nullable.GetUnderlyingType(propertyType) ?? propertyType);

// Does Not Work
var value = oldValue.To(propertyType);
```

Through debugging it, I have determined that the type converter is not calling the MyTypeConverter of the enum when I don't get the base nullable type.

**Comment by t-bruning** [comment]
Could you please give me the source code of your `MyTypeConverter`?

**Comment by t-bruning** [comment]
In fact, the conversion recursively calls itself with the underlying type if conversion to the original type does not work an it is a Nullable:

TypeConverter, line 212:
```
// if nullable -> try again with the underlying type:
if (destinationType.IsGenericNullable()) {
    var coreDestinationType = destinationType.GetUnderlyingType();
    return TryConvert(value, coreDestinationType, out result, args);
}
```

So it should already do what you are doing... I just tested it successfully with my own setup - similar to yours.

Please provide complete source code of a non working example and I'll have a look at it.

**Comment by ghost** [comment]
Here is the TypeConverter (well, [EnumConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.enumconverter?view=net-6.0) which is derived from TypeConverter)
```c#
public class StringEnumTypeConverter : EnumConverter {

    public StringEnumTypeConverter(Type type) : base(type) {
    }
    

    /// <inheritdoc />
    public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType) {
        if (destinationType != typeof(string))
            return base.ConvertTo(context, culture, value, destinationType);

        var fieldInfo = value?.GetType().GetField(value.ToString() ?? throw new InvalidOperationException());
        var attribute = fieldInfo?.GetCustomAttributes(typeof(DescriptionAttribute)).FirstOrDefault() as DescriptionAttribute;

        return (attribute is null || string.IsNullOrEmpty(attribute.Description)) ? value?.ToString()
            : attribute.Description;
    }

    /// <inheritdoc />
    public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value) {
        return value is string stringValue ? EnumFromDescription.GetEnum(stringValue, EnumType) : base.ConvertFrom(context, culture, value);
    }

}
```

Here is the EnumFromDescription class:
```C#
public static class EnumFromDescription {

    public static TEnum? GetEnum<TEnum>(string? description) {
        return (TEnum?)GetEnum(description, typeof(TEnum));
    }

    public static object? GetEnum(string? description, Type enumType) {
        if (description == null) return null;
        if (!enumType.IsEnum) throw new InvalidOperationException("Type must be an enum");

        var values = Enum.GetValues(enumType);

        foreach (var value in values) {
            var enumName = Enum.GetName(enumType, value);
            if (enumName == null) throw new NullReferenceException("Could not get enum name");

            var memberinfos = enumType.GetMember(enumName);
            var memberinfo = memberinfos?.FirstOrDefault(m => m.DeclaringType == enumType);
            var attributes = memberinfo?.GetCustomAttributes(typeof(DescriptionAttribute), false);
            var attributedescription = ((DescriptionAttribute?)attributes?[0])?.Description;

            if (attributedescription == null) throw new NullReferenceException("Unable to get description from enum");

            if (attributedescription.Equals(description, System.StringComparison.OrdinalIgnoreCase)) {
                return value;
            }
        }

        return default;
    }

}
```

**Comment by t-bruning** [comment]
Please confirm that you only have problems with converting an empty string?

I added a test/demo - integrating your source code:  
https://github.com/t-bruning/UniversalTypeConverter/blob/4-nullable-enums-dont-use-typeconverter-attribute/src/UniversalTypeConverter.Tests/_Git4_Nullable_Enums_Do_Not_Use_TypeConverter_Attribute.cs

As you can see, converting from "OTHER" works as expected.

BUT: converting from an empty string will return null. I assume that you expected it to return "YourEnum.General"...?

Let me explain:  
You are declaring a Nullable<YourEnum> as destination type. In fact, this is a type on its own and it does not know anything about your TypeConverterAttribute. But the System/Framework provides a NullableConverter by default for these types. If you have a look at the [source code of the NullableConverter](https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/NullableConverter.cs) you will see that it handles an empty string as null. So the UniversalTypeConverter does what it is designed for - but maybe not what you expect in regard to this special case.

I recommend you to register a custom mapping for this case as mentioned in the test/demo:

```
TestEnum? myDefault = TestEnum.General;
TB.ComponentModel.UniversalTypeConverter.ValueMappings.Add(string.Empty, myDefault);
```

You only have to add it once - e.g. at program start up.

Does it help you?

**Comment by t-bruning** [comment]
ghost won't answer
