### ISSUE TITLE
Throw exception when object to convert is null

### ISSUE THREAD

**Issue by ivanzanolla** [t-bruning/UniversalTypeConverter#5]
Hello there,

I wrapped your code to have a unique extension method without reference yours everytime I need, such as

		public static T As<T>(this object value, CultureInfo culture = null)
		{
			return ObjectExtension.As<T>(value, culture).OrDefault();
		}

		public static bool IsConvertibleTo<T>(this object value, CultureInfo culture = null)
		{
			return ObjectExtension.IsConvertibleTo<T>(value, culture);
		}

 this new version 2.6.0 raises exception when the object to convert is null, the old one doesn't do it. I would rather it to return the default (e.g. the default or return false when the conversion is impossible) as the old one

Thanks

**Comment by t-bruning** [comment]
Hi,

you have to configure your converter:

`TB.ComponentModel.UniversalTypeConverter.Options.AllowDefaultValueIfNull = true;`

You only have to do it once - e.g. at program start up.  
Is this what you're looking for?

You may also want to set this option:

`TB.ComponentModel.UniversalTypeConverter.Options.AllowDefaultValueIfWhitespace = true;`

**Comment by ivanzanolla** [comment]
Hi,

Not yet, 

   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) in f:\dd\ndp\clr\src\BCL\system\globalization\datetimeparse.cs:line 2282

When string is "".

**Comment by t-bruning** [comment]
You may also want to set this option:

`TB.ComponentModel.UniversalTypeConverter.Options.AllowDefaultValueIfWhitespace = true;`

**Comment by ivanzanolla** [comment]
UniversalTypeConverter.Options.AllowDefaultValueIfNull = true;
			UniversalTypeConverter.Options.AllowDefaultValueIfWhitespace = true;
			UniversalTypeConverter.Options.AllowDefaultValueIfNotConvertible = true;


I tried this above, nothing change

**Comment by t-bruning** [comment]
OK, would you please provide full stack trace of your exception?  
A small demo projekt reproducing your error would be helpfull as well.

**Comment by t-bruning** [comment]
Just to let you know: I'll be back to you after Christmas ;-) - have a great time!

**Comment by ivanzanolla** [comment]
Actually, I can't reproduce the issue in a clean project as a simple console application, I'm going to go further and If I get some other details I'll inform you. Happy holidays!

**Comment by t-bruning** [comment]
Fine, so I will close the ticket until you can provide something reproducible.
