### ISSUE TITLE
Conversion of ReadOnlySpan strings?

### ISSUE THREAD

**Issue by jas88** [t-bruning/UniversalTypeConverter#6]
It's very useful to try converting "strings" to integers, dates etc, but using a ReadOnlySpan<char> rather than a String object avoids copying when parsing or splitting - but that doesn't work cleanly with the current UniversalTypeConverter since that expects object types and ReadOnlySpan is a ref struct not an object. Would it be possible to get ReadOnlySpan<char> methods somehow please?

**Comment by t-bruning** [comment]
Just to be sure: by `ReadOnlySpan` you mean `ReadOnlySpan<char>`, right?

So for now the following code will work as a workaround?
`mySpan.ToString().To<int>()`

Please confirm so that I have a clear idea of your use case.

**Comment by jas88** [comment]
That works, yes, but the point of `ReadOnlySpan<char>` instead of `string` is that it avoids a lot of copying for parsing and splitting strings. Our use case for UTC is a database library which is handling a terabyte or more of SQL in some installations, so chucking extra strings around with boxing and allocation/GC overhead is something we'd like to avoid if possible.

It's why the built in methods like int.TryParse have `ReadOnlySpan<char>` versions now - more efficient than passing strings around. int.TryParse(mySpan,out var myInt) avoids allocations, and can be done on slices directly when I have multiple `int`s in a string; using `Split` then passing each to UTC as-is means allocating a new `string` per section, an `Array`, then auto-boxing each `string` into an `object` - a whole lot of extra overhead.

**Comment by t-bruning** [comment]
The reason for this is, of course, that Span cannot be assigned to an object variable. The support of ReadOnlySpan<char> seems to make sense to me. However, overloading all methods requires some work, ~~which I can only do slowly~~. I'll get back to you when I've implemented it.

**Comment by t-bruning** [comment]
@jas88 I opened a pull request https://github.com/t-bruning/UniversalTypeConverter/pull/7 - maybe you have the time to check it against your use case?
I will do some more testing but I am looking forward to release a new nuget-Package next week.

**Comment by jas88** [comment]
Thanks Thorsten, that's good to see, looks like a nice enhancement.
