### ISSUE TITLE
Request: Add Guid to byte[] conversion

### ISSUE THREAD

**Issue by swidz** [t-bruning/UniversalTypeConverter#8]
Guid type has a native method [Guid.ToByteArray](https://learn.microsoft.com/en-us/dotnet/api/system.guid.tobytearray?view=netstandard-2.0) .

Such conversion is often used e.g. when saving Guid fields to Sqlite database which has no native support for Guids thus conversion to TEXT (string) or to BINARY (byte[]) is required.

Would it be possible to add native conversion in future releases of Universal Type Converter?

Regards,
Sebastian

**Comment by t-bruning** [comment]
Thank you for describing your use case - this makes sense to me.  
I will gladly include it in the next release.

**Comment by t-bruning** [comment]
There is a new version of the UniversalTypeConverter supporting Guid to byte[].
